# building the containrs in the subdirectory

version: '3.8'
services:
  ux-interview-backend:
    container_name: ux-interview-backend
    networks:
      - my-network
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  ux-interview-frontend:
    container_name: ux-interview-frontend
    networks:
      - my-network
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - ux-interview-backend
networks:
  my-network:
    driver: bridge

